# Generated by Django 4.1.7 on 2023-04-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(default='pug.jpg', upload_to=''),
        ),
    ]
